name: Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      PIP_DOWNLOAD_CACHE: ${{ github.workspace }}/../.pip_download_cache
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install deps with brew
      if: runner.os == 'macOS'
      run: |
        brew install -s re2
        brew install pybind11 ninja

    - name: Install PPA and build deps
      if: runner.os == 'Linux'
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y -s ppa:nerdboy/embedded
        sudo apt-get install -y pybind11-dev libre2-dev ninja-build

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install tox

    # order is important here due to multiple cmake cache files left under build/
    - name: Test in place
      run: |
        tox -e py
    - name: Install and test
      run: |
        tox -e dev
    - name: Build dist pkgs
      run: |
        tox -e deploy
